import { IsInt, IsUUID, Min } from 'class-validator'

/**
 * The minimum a rendered public page sends to record one view.
 *
 * The body carries idempotency and version context only. Everything else about an event
 * — time, address, browser, operating system, language, country and whether it is
 * synthetic — is resolved by the server, so none of it is accepted here. The global
 * validation pipe rejects unknown properties, which keeps that boundary explicit rather
 * than relying on callers to behave.
 *
 * `version` is the public version number the page actually rendered. It lets a page
 * loaded immediately before a republish record the version it displayed instead of
 * whichever version happens to be current when the event arrives. It is a public
 * version number, never an internal version id, and the server proves it belongs to the
 * passport before using it.
 */
export class ViewEventDto {
  /** A UUID generated by the page navigation and reused verbatim on retry. */
  @IsUUID()
  eventKey!: string

  @IsInt()
  @Min(1)
  version!: number
}
